### ISSUE TITLE
No Changelog

### ISSUE THREAD

**Issue by djmitche** [hapijs/hawk#265]
#### Context

* *node version*: n/a
* *module version*:  n/a

#### What are you trying to achieve or the steps to reproduce ?

The CHANGELOG.md file points to an empty list of issues, making it difficult to see what has changed in which release.  It would be ideal if this information were summarized in the GitHub releases or in CHANGELOG.md itself.

**Comment by hueniverse** [comment]
Its standard for the entire org. Either way, I am not expecting changes to this. It's pretty much done.

**Comment by djmitche** [comment]
I'm confused -- the changlog points to an empty list, yet releases have been made, so *something* is wrong here.

**Comment by djmitche** [comment]
To be clear, Hawk is a *very* important part of our (and probably other projects') security model.  It's pretty terrifying when something so fundamental says "we'll change stuff but we're too busy to tell you what".

**Comment by hueniverse** [comment]
Just because there isn't a nicely edited change log doesn't mean it is not properly documented. Every issue is assigned a milestone and you can easily see what has changed. The changelog uses a label that has not been used in this repo as it was moved from another account with a different setup. You can still find all the information in the milestones.
